---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure zsh package exists
      ansible.builtin.package:
        name: zsh
        state: present
    - name: Ensure there is a ~/.zshrc
      ansible.builtin.copy:
        src: zshrc
        dest: ~/.zshrc
        mode: '0644'
