---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    zim_zshrc: "/root/.zshrc"
  gather_facts: false
  tasks:
    - name: "Test zim:fw - test that ~/.zshrc has been modified"
      block:
        - name: "Test zim:fw - retrieve information from path '{{ zim_zshrc }}'"
          ansible.builtin.stat:
            path: "{{ zim_zshrc }}"
          register: remote_file

        - name: "Test zim:fw - assert that file is created correctly '{{ zim_zshrc }}'"
          ansible.builtin.assert:
            that:
              - "remote_file.stat.exists"
              - "remote_file.stat.isreg" # is a regular file
              - "remote_file.stat.path == '{{ zim_zshrc }}'"
              - "remote_file.stat.mode == '0644'"
