---
- name: Ensure ~/.zshrc exists
  ansible.builtin.file:
    path: ~/.zshrc
    state: touch
  when: configure_zim

- name: Insert/Update "Zim:FW init" in .zshrc
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    block: |
      zstyle ':zim:zmodule' use '{{ zim_zmodule_tool }}'

      ZIM_HOME={{ zim_home }}
      # Download zimfw plugin manager if missing.
      if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
        curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
            https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
      fi

      # Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
      if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
        source ${ZIM_HOME}/zimfw.zsh init -q
      fi

      # Initialize modules.
      source ${ZIM_HOME}/init.zsh
    backup: yes
    state: present
  when: configure_zim
