---
- name: Ensure ~/.zshrc exists
  ansible.builtin.stat:
    path: "{{ zim_user_dir }}/.zshrc"
  register: zshrc_stat
  when: configure_zim

- name: "Install Zim:FW"
  block:
    - name: "zim:fw - Create .ziminit.zsh"
      ansible.builtin.template:
        src: ziminit.zsh.j2
        dest: "{{ zim_user_dir }}/{{ zim_init_file }}"
        owner: "{{ zim_user }}"
        group: "{{ zim_user }}"
        mode: "0644"
      tags: ziminit

    - name: "Zim:FW - Create simple .zimrc"
      ansible.builtin.copy:
        src: zimrc
        dest: "{{ zim_user_dir }}/.zimrc"
        owner: "{{ zim_user }}"
        group: "{{ zim_user }}"
        mode: "0644"
      tags: zimrc

    - name: Insert/Update "Zim:FW init" in .zshrc
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        block: "{{ zim_zshrc_injection }}"
        backup: yes
        insertbefore: "BOF"
        state: present
      tags: zshrc

  when: configure_zim and zshrc_stat.stat.exists
